#!/usr/bin/env python
import sys
import os

from kdecore import KCmdLineArgs

from application import MainApplication, AboutData
from base import excepthook

from mainwin import MainWindow


if __name__ == '__main__':
    aboutData = AboutData()
    KCmdLineArgs.init(sys.argv, aboutData)
    #install excepthook here
    sys.excepthook = excepthook

    app = MainApplication()
    win = MainWindow(None)
    win.systray.show()

    app.setMainWidget(win)
    #import pdb
    #pdb.set_trace()
    app.exec_loop()
    
