#!/bin/bash
# this file should be run from the webroot

echo "building index"
rst2html src/index > index.html
echo "building notes"
rst2html ../paella/notes > notes.html
echo "building gui"
rst2html src/gui > gui.html

